sim:
  ros__parameters:
    lqr_param_list: ["lqr_gain_row_num", "lqr_gain_col_num", "lqr_K"]
    lqr_gain_row_num: 1
    lqr_gain_col_num: 4
    lqr_K: [-8.82,-13.24,65.9,12.0]

controller_node:
  ros__parameters:
    lqr_param_list: ["lqr_gain_row_num", "lqr_gain_col_num", "lqr_K"]
    lqr_gain_row_num: 1
    lqr_gain_col_num: 4
    lqr_K: [-8.82,-13.24,65.9,12.0]
