sim:
  ros__parameters:
    urdf_joint_total: ["world_to_ground_joint","cart_joint","pole_joint","pole_to_tip_joint"]
    urdf_joint_type: ["fixed","prismatic","continuous", "fixed"]
    model_name: "cart_pole"


excel_record_logging:
  ros__parameters:
    urdf_joint_ignore: ["world_to_ground_joint","pole_to_tip_joint"]
    urdf_joint_total: ["world_to_ground_joint","cart_joint","pole_joint","pole_to_tip_joint"]
    model_name: "cart_pole"